### ISSUE TITLE
lib/Makefile problems

### ISSUE THREAD

**Issue by dchmelik** [AmyBSOD/ToME-SX#1]
The makefile.std has a bad LIBDIR, ‘./lib.’ When someone tries to build a package with your source code, their build script will usually have problems with that. Often a build script will make something like /tmp/program-name and /tmp/program-name$LIBDIR. This ends up that it makes /tmp/program-name./LIBDIR and so that is lost to the package. It's not good to use ‘.’ in a path unless it's actually there. Fortunately you can override this with ‘make $LIBDIR.’

I managed to do that, but then tome won't set up the game because it's looking for nonexistent Lua files in /lib. Either something went wrong, maybe the program using old Lua, or not being able to use the proper lib directories (often /lib64 or /usr/lib64) or you haven't listed dependencies. I can't copy those start errors into here, since there's no ‘tome -mgcu,’ which means I probably wouldn't play it much, but I'd still like to make a SlackBuild so people can build and install a ToME-SX package on Slackware GNU/Linux.

**Comment by AmyBSOD** [comment]
Thanks for the feedback. Unfortunately I haven't tried to get it to compile on a Linux system yet (I'm on Windows where it compiles fine); I'm afraid this error has already been in ToME 2.3.5, the one on which I based my fork, and I'm not familiar enough with the build system to fix it myself, but if you can make a pull request that fixes it then I'll gladly implement it! :)

**Comment by dchmelik** [comment]
Actually, I compiled, played ToME 2.3.5 and made a SlackBuild [https://slackbuilds.org/repository/13.0/games/tome/](https://slackbuilds.org/repository/13.0/games/tome/) for it on Slackware 13, years ago. It didn't have a problem finding the right library files.  Maybe I had to set $LIBDIR, but that would've been all.

**Comment by dchmelik** [comment]
Yes, it was something I did wrong with $LIBDIR, while comparing tome-ah cmake code with the old regular make code. I have figured it out now and will release a SlackBuild shortly so people can automatically build & install your variant on Slackware GNU/Linux.
